### ISSUE TITLE
Error in updating QC settings

### ISSUE THREAD

**Issue by MichielVieijra** [vergauwenthomas/MetObs_toolkit#156]
Fix error in updating of QC settings.

**Comment by vergauwenthomas** [comment]
The problem is that when updating the setting of an dataset instance, it will propagate to other dataset instances (when initialization is after the update of the other dataset). 

I guess that the settings class got updated when updating an instance of it, somehow ... strange because the setting are not class variables.

**Comment by vergauwenthomas** [comment]
Because the attribute is actually a pointer, the solution was to apply a deepcopy on init.
